# Generated by Django 6.0.5 on 2026-05-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=20)),
                ('EmployeeDepartment', models.CharField(blank=True, max_length=20, null=True)),
                ('Country', models.CharField(blank=True, max_length=20, null=True)),
                ('Salary', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
