# Generated by Django 6.0.5 on 2026-06-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T5_List_View_Function_based_Views_Django', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='raj',
            new_name='T5_List_view_function_raj',
        ),
    ]
