"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kzpq#4tkyw7!h+_yfc%44!#ql9u8fk-h3l*%x!sn^x4#5_uecy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DjangoApp',  # Added the DjangoApp
    'T2',   # Added the T2 App
    'T3',   # Added the T3 App
    'T4',    # Added the T4 App
    'T5_views_in_django',   # Added the T5_views_in_django App
    'T5_Django_Function_Based_Views',   # Added the T5_Django_Function_Based_Views App
    'T5_Create_View_Function_based_Views_Django',   # Added the T5_Create_View_Function_based_Views_Django App
    'T5_List_View_Function_based_Views_Django',   # Added the T5_List_View_Function_based_Views_Django App
    'T5_Detail_View_Function_based_Views_Django',   # Added the T5_Detail_View_Function_based_Views_Django App
    'T5_Update_View_Function_based_Views_Django',   # Added the T5_Update_View_Function_based_Views_Django App
    'T5_Delete_View_Function_based_Views_Django',   # Added the T5_Delete_View_Function_based_Views_Django App
    'T6_Django_Class_Based_view',   # Added the T6_Django_Class_Based_view
    'T7_Django_Templates',  # Added the T7_Django_Templates 
    'T7_Variables_Django_Templates',   # Added the T7_Variables_Django_Templates
    'T7_Django_Template_Tags',    # Added the T7_Django_Template_Tags
    'T7_for_loop_Django_Template_Tags',   # Added the T7_for_loop_Django_Template_Tags
    'T7_if_and_else',     # Added the T7_if_and_else 
    'T7_Django_Boolean_Operations_and_Filters',    # Added the T7_Django_Boolean_Operations_and_Filters
    'T8_Django_Forms',   # Added the T8_Django_Forms
    'T8_Render_Django_Form_Fields_Manually',  # Added the T8_Render_Django_Form_Fields_Manually
    'T8_Handling_HTML_Forms_in_Django_GET_and_POST_Methods',  # Added the T8_Handling_HTML_Forms_in_Django_GET_and_POST_Methods
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
