# Generated by Django 5.1.5 on 2026-02-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RajModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raj_field', models.IntegerField()),
            ],
        ),
    ]
