# Generated by Django 5.1.5 on 2026-02-17 16:02

import T2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T2', '0002_rajmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='customField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=200, validators=[T2.models.validate_mail])),
            ],
        ),
    ]
